CREATE TABLE books (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(100) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  publisher VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  language VARCHAR(50) NOT NULL,
  isbn VARCHAR(50) NOT NULL UNIQUE,
  price DECIMAL(10, 2) NOT NULL,
  status VARCHAR(50) NOT NULL,
  cover VARCHAR(255) NOT NULL,
  summary VARCHAR(1000) NOT NULL,
  description TEXT NOT NULL,
  highlights TEXT NOT NULL
);

CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  twitter VARCHAR(100) NOT NULL,
  avatar_url VARCHAR(255),
  notes VARCHAR(1000),
  created_at TIMESTAMP NOT NULL
);
